version: "3.9"

services:
  # PHP + Apache container
  web:
    build: .
    container_name: plpsg-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: smartgrade
      DB_USER: root
      DB_PASS: rootpassword
    depends_on:
      - db

  # MySQL Database container
  db:
    image: mysql:8.0
    container_name: plpsg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartgrade
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # phpMyAdmin for managing the database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: plpsg-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
